### ISSUE TITLE
Another null htpp response 

### ISSUE THREAD

**Issue by nhanth87** [RestComm/ussdgateway#31]
```
2016-07-12 16:33:45,189 ERROR [javax.slee.SbbNotification[service=ServiceID[name=mobicents-ussdgateway,vendor=org.mobicents,version=1.0],sbb=SbbID[name=HttpClientSbb,vendor=org.mobicents,version=1.0]].USSD-Child-org.mobicents.ussdgateway.slee.http.HttpClientSbbImpl] (pool-38-thread-1) Error while processing RESPONSE event
java.lang.Exception: Error while processing 2xx
	at org.mobicents.ussdgateway.slee.http.HttpClientSbb.onResponseEvent(HttpClientSbb.java:173)
	at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mobicents.slee.runtime.sbbentity.SbbEntityImpl.invokeEventHandler(SbbEntityImpl.java:479)
	at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.routeQueuedEvent(EventRoutingTaskImpl.java:379)
	at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.run(EventRoutingTaskImpl.java:126)
	at org.mobicents.slee.runtime.eventrouter.EventRouterExecutorImpl$EventRoutingTaskStatsCollector.run(EventRouterExecutorImpl.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Received invalid payload from http server (null or zero length)
	at org.mobicents.ussdgateway.slee.http.HttpClientSbb.onResponseEvent(HttpClientSbb.java:114)
	... 10 more
2016-07-12 16:34:04,789 WARN  [javax.slee.SbbNotification[service=ServiceID[name=mobicents-ussdgateway,vendor=org.mobicents,version=1.0],sbb=SbbID[name=ParentSbb,vendor=org.mobicents,version=1.0]].USSD-Parent-org.mobicents.ussdgateway.slee.ParentSbbImpl] (pool-37-thread-1) No routing rule configured for short code=*27*99# and network id=0
```

- After that, USSD GW is not response anything back to the upstream and after some time, upstream send some sctp data retransmission and *BAN* our connection.

USSD GW should handle this exception and send back "server error"

**Comment by vetss** [comment]
@nhanth87 

we need try to reproduce it locally. Is it possible to reproduce ?

**Comment by nhanth87** [comment]
Hi @vetss I think yes,
We just need to modify simulator app that just sends 200OK with an empty body.
But I also saw this problem it on Charging Server too:
https://github.com/RestComm/charging-server/issues/4
