### ISSUE TITLE
java.lang.InternalError: should not reach here SctpChannelImpl

### ISSUE THREAD

**Issue by Rouanvdw** [RestComm/ussdgateway#37]
The USSD Gateway has for a few months with a few hiccups that we were able to work around. About to weeks ago we started getting the following error:

java.lang.InternalError: should not reach here
    at sun.nio.ch.sctp.SctpChannelImpl.receive0(Native Method)
    at sun.nio.ch.sctp.SctpChannelImpl.receiveIntoNativeBuffer(SctpChannelImpl.java:859)

If I google this is states that there is a JDK bug. I have tried multiple JDK and they all give the same error, Some times the gateway will run for few days before crashing and other times it crashes after an hour.

Any help would be appreciated.

**Comment by vetss** [comment]
Hello @Rouanvdw 

this looks like a low-level error. May be you need to update your OS level core / drivers.

**Comment by Rouanvdw** [comment]
Hello @vetss 

But would this be required if everything was running fine and then suddenly it started giving this issue?
