### ISSUE TITLE
GUI: Campaign deletion doesn't work when created with special characters

### ISSUE THREAD

**Issue by FerUy** [RestComm/ussdgateway#52]
After creating a campaign with a special character like `ñ` (from Spanish alphabet, *Campa**ñ**a* means *Campaign* in Spanish), the name is not shown as created, and worse, it is not possible to remove it in the GUI, an exception is thrown. See attached image and stack trace below.

![campaign_deletion_failure](https://cloud.githubusercontent.com/assets/14883482/23732417/02094d74-0441-11e7-9452-5e536394f007.png)

`
java.lang.Exception: Campaign CampaÃÂ±a not found
	at org.mobicents.protocols.ss7.oam.common.statistics.CounterProviderManagement.destroyCampaign(CounterProviderManagement.java:276)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:668)
	at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:98)
	at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:40)
	at org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:87)
	at org.jolokia.backend.MBeanServerExecutorLocal.handleRequest(MBeanServerExecutorLocal.java:139)
	at org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:101)
	at org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:90)
	at org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:377)
	at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:147)
	at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:195)
	at org.jolokia.http.HttpRequestHandler.handleGetRequest(HttpRequestHandler.java:86)
	at org.jolokia.http.AgentServlet$3.handleRequest(AgentServlet.java:293)
	at org.jolokia.http.AgentServlet.handle(AgentServlet.java:225)
	at org.jolokia.http.AgentServlet.doGet(AgentServlet.java:190)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:190)
	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:92)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:598)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by vetss** [comment]
Thanks @FerUy for bug reporting, we need to check it.

**Comment by FerUy** [comment]
You're welcome @vetss.

Just fyi, I edited the xml file and changed "Campa**Ã±**a" for "Campa**ni**a", restarted and then I was able to delete it from the GUI (this was important to do, as stats.log file was recording data for this obsolete campaign).
