### ISSUE TITLE
NPE when rawContent is null

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/ussdgateway#54]
only reproducible if log is debug level
rawContent

[Message] Error while processing BYE event 
RequestEventWrapper[ EVENT[BYE] DIALOG[ClientDialogWrapper[ handle = 9e6d60a5b8afaf84f5e3713139b90771@10.0.0.9:4909:null, state = Terminated Dialog, clientTXs = [] ]] TX[ServerTransaction[z9hG4bKc7045a3a_57a5b08a_a876eafd-c6e8-459e-a5a2-48a1f8478bd6]]]
java.lang.NullPointerException
	at java.lang.String.<init>(String.java:556)
	at org.mobicents.ussdgateway.slee.sip.SipClientSbb.onCallTerminated(SipClientSbb.java:334)
	at sun.reflect.GeneratedMethodAccessor360.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mobicents.slee.runtime.sbbentity.SbbEntityImpl.invokeEventHandler(SbbEntityImpl.java:479)
	at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.routeQueuedEvent(EventRoutingTaskImpl.java:381)
	at org.mobicents.slee.runtime.eventrouter.routingtask.EventRoutingTaskImpl.run(EventRoutingTaskImpl.java:128)
	at org.mobicents.slee.runtime.eventrouter.EventRouterExecutorImpl$EventRoutingTaskStatsCollector.run(EventRouterExecutorImpl.java:72)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[Emitter]

**Comment by vetss** [comment]
Fixing by:
https://github.com/RestComm/ussdgateway/commit/149482cced9998e4e6c91725d8e309b7975d0faf
