### ISSUE TITLE
Jolokia request failed: javax.management.InstanceNotFoundException 

### ISSUE THREAD

**Issue by parsibox** [RestComm/ussdgateway#98]
hi
i install ussdgateway with wildfly-10.1.0.Final
when i go to to panel it say
```
Jolokia request failed: javax.management.InstanceNotFoundException : org.mobicents.ussdgateway:name=ShortCodeRoutingRuleManagement
```
![image](https://user-images.githubusercontent.com/12513476/105822135-ee40ea00-5fd0-11eb-9b4c-d613481c50fd.png)

**Comment by parsibox** [comment]
```


javax.management.InstanceNotFoundException: org.mobicents.ussdgateway:name=UssdPropertiesManagement
	at org.jboss.as.jmx.PluggableMBeanServerImpl.findDelegate(PluggableMBeanServerImpl.java:1110)
	at org.jboss.as.jmx.PluggableMBeanServerImpl.getMBeanInfo(PluggableMBeanServerImpl.java:578)
	at org.jboss.as.jmx.PluggableMBeanServerImpl.getMBeanInfo(PluggableMBeanServerImpl.java:570)
	at org.jolokia.handler.ReadHandler$1.execute(ReadHandler.java:46)
	at org.jolokia.handler.ReadHandler$1.execute(ReadHandler.java:41)
	at org.jolokia.backend.executor.AbstractMBeanServerExecutor.call(AbstractMBeanServerExecutor.java:85)
	at org.jolokia.handler.ReadHandler.getMBeanInfo(ReadHandler.java:226)
	at org.jolokia.handler.ReadHandler.getAllAttributesNames(ReadHandler.java:238)
	at org.jolokia.handler.ReadHandler.resolveAttributes(ReadHandler.java:210)
	at org.jolokia.handler.ReadHandler.fetchAttributes(ReadHandler.java:178)
	at org.jolokia.handler.ReadHandler.doHandleRequest(ReadHandler.java:119)
	at org.jolokia.handler.ReadHandler.doHandleRequest(ReadHandler.java:37)
	at org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:159)
	at org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:96)
	at org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:90)
	at org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:377)
	at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:147)
	at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:195)
	at org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:131)
	at org.jolokia.http.AgentServlet$2.handleRequest(AgentServlet.java:283)
	at org.jolokia.http.AgentServlet.handle(AgentServlet.java:225)
	at org.jolokia.http.AgentServlet.doPost(AgentServlet.java:197)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Close 
```

**Comment by Lundmatt** [comment]
Hi @parsibox,
Did you resolve this issue?

**Comment by parsibox** [comment]
no i used only library
this application is wrong
